### PR TITLE
Restrict size of batch payloads to 256kb dynamically

### PR DESCRIPTION
**Pull request by jarro2783**
This is logstash-plugins/logstash-output-sqs#4 rebased onto master and squashed (to fix merge issues).

### CODE REVIEW

**Comment by martinssipenko** [comment]
This should fix #5

**Comment by holmjoel** [comment]
Hi, I wonder if there's a plan to merge this? 

From the travis output It looks like dependency issues causing the fail and there aren't any changes to dependencies in the PR as far as I can tell.

Does the build work for master?

Cheers,
Joel

**Comment by joshuaspence** [comment]
Any plans on merging this?

**Comment by jrgns** [comment]
Closing this in favour of #20

**Comment by jarro2783** [comment]
Yep sounds good.

**Pull request closed without merging**
