### PR TITLE
AWS Ruby SDK v2 upgrade

### PR DESCRIPTION
**Pull request by dwagner2301**
.gemspec-file changed to include v2 of the aws ruby sdk.
sqs.rb changed to make use of the changed api-calls.

### CODE REVIEW

**Comment by dwagner2301** [comment]
@ph formal tests are still missing. But I would be happy to provide those if I could get some help (it's the same for the logstash-input-sqs plugin).

**Comment by ph** [comment]
@dwagner2301 for the test can you take a look at the SQS input, I've created a bunch for it and I think it's a good start.

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by jrgns** [comment]
Closing this in favour of #20

**Pull request closed without merging**
