### PR TITLE
Update sample policy as its very confusing.

### PR DESCRIPTION
**Pull request by azdlowry**

### CODE REVIEW

**Comment by ph** [comment]
You are right this is confusing!

Would you mind doing step 2 of the contributing guide? https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by azdlowry** [comment]
jenkins, test it

**Comment by ph** [comment]
@azdlowry Thanks I just merged it, it will appear when we generate the new documentations.

**Pull request closed without merging**
