### PR TITLE
This plugin require the aws mixin to be higher than 1.0.0

### PR DESCRIPTION
**Pull request by ph**

### CODE REVIEW

**Comment by ph** [comment]
@jrgns Did you push a new release of the sqs and the cloudwatch with my fixes?

**Comment by jrgns** [comment]
@ph No, I haven't pushed a new release yet. I can do it now?

**Comment by ph** [comment]
I think we should, can you update the corresponding changelog and make the
releases.

On Thu, Apr 14, 2016 at 5:43 PM, Jrgns notifications@github.com wrote:

> No, I haven't pushed a new release yet. I can do it now?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/logstash-plugins/logstash-output-sqs/pull/12#issuecomment-210163501

## 

## 

ph
Software Engineer

**Comment by jrgns** [comment]
I've updated the necessary files in #13 , but can't push / publish the gem :(

@acchen97 / @ph can you either publish the latest version, or give me permission to do so?

**Comment by ph** [comment]
I just pushed the new plugin and will sync with @acchen97 for a followup

**Pull request merged**
