### PR TITLE
Mark deprecated `batch` and `batch_timeout` options as obsolete

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by jakelandis** [comment]
It looks like ```batch``` is still used by a spec: https://github.com/logstash-plugins/logstash-output-sqs/blob/37f913a31d1892d38d09b99fec4d5ee95042b8de/spec/integration/outputs/sqs_spec.rb#L75

**Comment by jsvd** [comment]
ugh, nice catch 👍

**Comment by untergeek** [comment]
`batch` still hasn't been removed from the spec tests:
```
Failed examples:
rspec ./spec/unit/outputs/sqs_spec.rb:159 # LogStash::Outputs::SQS#multi_receive_encoded with batching enabled should batch events
rspec ./spec/unit/outputs/sqs_spec.rb:154 # LogStash::Outputs::SQS#multi_receive_encoded with batching enabled should call send_message_batch
rspec ./spec/unit/outputs/sqs_spec.rb:108 # LogStash::Outputs::SQS#multi_receive_encoded with batching disabled using the `batch` parameter should not call send_message_batch
rspec ./spec/unit/outputs/sqs_spec.rb:103 # LogStash::Outputs::SQS#multi_receive_encoded with batching disabled using the `batch` parameter should call send_message
rspec ./spec/unit/outputs/sqs_spec.rb:122 # LogStash::Outputs::SQS#multi_receive_encoded with batching disabled should call send_message
rspec ./spec/unit/outputs/sqs_spec.rb:127 # LogStash::Outputs::SQS#multi_receive_encoded with batching disabled should not call send_message_batch
```

**Comment by jsvd** [comment]
references to batch removed, tests passing

**Comment by jakelandis** [comment]
LGTM

**Pull request merged**
